### ISSUE TITLE
autoload without namespace

### ISSUE THREAD

**Issue by GuillaumeSeren** [php-fedora/autoloader#15]
Hi there !
I used autoloader to package composer in gentoo (https://github.com/gentoo/gentoo/pull/2905),
it went well and it is merged in the main tree now, so thank you for making this lib it helped me a lot.

I am now working on phpunit and some package like https://github.com/sebastianbergmann/php-timer didn't have namespace declaration in the lib, so I am wondering what could be the best usage, to load it with the autoloader (for consistency sake).

**Comment by remicollet** [comment]
From php-timer's [composer.json ](https://github.com/sebastianbergmann/php-timer/blob/master/composer.json)

```
    "autoload": {
        "classmap": [
            "src/"
        ]
    }
```

So, in this case, best way is to generate a classmap autoloader.

Simplest solution is probably to use the phpab command from [theseer/autoload](https://github.com/theseer/Autoload).

For simplicity (but not mandatory), in Fedora we drop the `res/phpab/fedora.php.tpl` in `/usr/share/php/TheSeer/Autoload/templates/ci` and use:

`
phpab --template fedora --output  PHP/Timer/Autoload.php  PHP
`

Other solution for non namespaced library is to use addPsr0 (but not suitable in php-timer case, you have to follow composer information, so classmap).

**Comment by remicollet** [comment]
Example (for sebastian/environment) see http://pkgs.fedoraproject.org/cgit/rpms/php-phpunit-environment.git/tree/php-phpunit-environment.spec#n66

**Comment by GuillaumeSeren** [comment]
Hey Remi ! 🎄 
Thanks for the detailed reply, I will use phpab to overcome this 'no namespace' issue.

**Comment by remicollet** [comment]
BTW, I think I have tried to explained, there is no "'no namespace' issue."

See: https://github.com/php-fedora/autoloader/blob/master/tests/AutoloadTest.php#L135

phpab is not a "workaround', it's a way to manage "classmap" (no matching between class and file names, which is slightly different than PSR-0)

**Comment by GuillaumeSeren** [comment]
@remicollet Sorry I just discovered classmap loader lately,
I thought everything use a namespace now.

But yeah I understand the idea, I am packaging phpab first then I will try it with php-timer.

**Comment by remicollet** [comment]
Can I close this issue ?

**Comment by GuillaumeSeren** [comment]
Yes thank you 👍
