### ISSUE TITLE
multi autoloader with alternative versions

### ISSUE THREAD

**Issue by remicollet** [php-fedora/autoloader#16]
We are going to have need for this when multiple components are required and available as multiple versions, to avoid mixing component from different versions

We cannot use:

```
     \Fedora\Autoloader\Dependencies::required(array(
    array(
        "/usr/share/php/Symfony3/Component/Console/autoload.php",
        "/usr/share/php/Symfony3/Component/DependencyInjection/autoload.php",
    ),
    array(
        "/usr/share/php/Symfony/Component/Console/autoload.php",
        "/usr/share/php/Symfony/Component/DependencyInjection/autoload.php",
    )));
```

Workaround:

```
     if (!file_exists($dir = '/usr/share/php/Symfony3') $dir =  '/usr/share/php/Symfony';
     \Fedora\Autoloader\Dependencies::required(array(
        "$dir/Component/Console/autoload.php",
        "$dir/Component/DependencyInjection/autoload.php",
    ));
```

BTW, we perhaps have to stick with a single version in this case, as we also don't have any way to describe such requirement on RPM side.

**Comment by remicollet** [comment]
Another Workaround, use the global autoloader for the framework:

```
     \Fedora\Autoloader\Dependencies::required(array(
        array(
            "/usr/share/php/Symfony3/autoload.php",
            "/usr/share/php/Symfony/autoload.php",
        )));

```

**Comment by siwinski** [comment]
Perhaps we need to include something in the frameworks themselves to ensure they conflict with each other when both autoloaders are loaded?  And we could add RPM conflicts for the 2 Symfony pkgs for before the autoloader conflicts were added?  I'd rather just keep the logic in the frameworks themselves than putting more logic in each autoloader that uses the Symfony autoloaders or in this autoloader pkg.

Regarding the global autoloader for the Symfony framework, the only issue would be the dependencies of each component/bridge/bundle as we'd need to load every dependency of each of those individual pkgs.

Overall, I'm not sure this is an issue with this autoloader pkg but is more of an issue with the usage of individual pkg/framework autoloaders instead.

**Comment by remicollet** [comment]
> Overall, I'm not sure this is an issue with this autoloader pkg but is more of an issue with the usage of individual pkg/framework autoloaders instead.

Indeed, I agree.
