### ISSUE TITLE
How to handle composer's files array?

### ISSUE THREAD

**Issue by irreleph4nt** [php-fedora/autoloader#18]
Hi,
I have searched far and wide for documentation on the fedora autoloader but can't find any good one for a first-time-php-packager on Fedora. 
I am having this particular issue: the software I am packaging has a files array in it's composer.json under autoload. How do I handle this with fedora autoloader or for packaging on Fedora in general? These files belong to no specific namespace as far as I can tell.

Project in question: [Kopano kdav](https://github.com/Kopano-dev/kdav)

**Comment by remicollet** [comment]
For such project, you need

```
        "psr-4" : {
            "Kopano\\DAV\\" : "lib/"
        },

```

* `\Fedora\Autoloader\Autoload::addPsr4` or generate a classmap (`phpab`)

`        "files" : ["config.php", "version.php", "mapi/mapi.util.php", "mapi/mapicode.php", "mapi/mapidefs.php", "mapi/mapiguid.php", "mapi/mapitags.php", "mapi/class.baserecurrence.php", "mapi/class.recurrence.php", "mapi/class.freebusypublish.php"]`

* Include (`require_once`) them, or use `\Fedora\Autoloader\Dependencies::required`

See php-alcaeus-mongo-php-adapter, php-phpmyadmin-sql-server, php-symfony-polyfill for examples

**Comment by remicollet** [comment]
Old one, not an issue
